"""v3 command factories; globals populated by scripts.train."""
def build_command(config, data):
    sft = config['sft']
    cmd = [
        'swift', 'sft',
        '--model', str(MODEL), '--model_type', 'qwen3', '--template', 'qwen3',
        '--dataset', str(data), '--tuner_type', 'lora',
        '--lora_rank', str(sft['rank']), '--lora_alpha', str(sft['alpha']),
        '--target_modules', sft['target_modules'],
        '--torch_dtype', sft['torch_dtype'], '--fp16', 'false', '--bf16', 'false',
        '--attn_impl', sft['attention_implementation'], '--max_length', str(sft['max_length']),
        '--truncation_strategy', 'delete', '--loss_scale', sft['loss_scale'],
        '--add_non_thinking_prefix', 'true', '--gradient_checkpointing', 'true',
        '--per_device_train_batch_size', str(sft['batch_size']),
        '--gradient_accumulation_steps', str(sft['gradient_accumulation_steps']),
        '--num_train_epochs', str(sft['epochs']), '--max_steps', str(sft['optimizer_steps']),
        '--learning_rate', str(sft['learning_rate']), '--warmup_ratio', str(sft['warmup_ratio']),
        '--split_dataset_ratio', '0', '--dataset_num_proc', '1',
        '--dataloader_num_workers', '0', '--dataloader_persistent_workers', 'false',
        '--dataset_shuffle', 'false', '--train_dataloader_shuffle', 'false',
        '--packing', 'false', '--padding_free', 'false',
        '--logging_steps', '10', '--save_strategy', 'steps',
        '--save_steps', '175', '--save_total_limit', '5',
        '--seed', str(sft['seed']), '--data_seed', str(sft['data_seed']),
        '--report_to', 'none', '--output_dir', str(OUT),
    ]
    return cmd

def arguments(config, variant, seed, steps, data, output):
    method = config['grpo']
    return {
        'rlhf_type': 'grpo', 'model': str(MODEL), 'model_type': 'qwen3',
        'template': 'qwen3', 'dataset': [str(data)], 'adapters': [str(ADAPTER)],
        'tuner_type': 'lora', 'lora_rank': config['sft']['rank'],
        'lora_alpha': config['sft']['alpha'], 'target_modules': ['all-linear'],
        'reward_funcs': ['finreason_v3_execution'],
        'callbacks': ['finreason_v3_audit'],
        'external_plugins': [str(PLUGIN)],
        'torch_dtype': method['torch_dtype'], 'bf16': method['bf16'],
        'fp16': method['fp16'], 'attn_impl': method['attention_implementation'],
        'max_length': 4096, 'truncation_strategy': 'delete',
        'loss_scale': config['sft']['loss_scale'],
        'add_non_thinking_prefix': method['add_non_thinking_prefix'],
        'enable_thinking': False, 'gradient_checkpointing': True,
        'per_device_train_batch_size': 1,
        'gradient_accumulation_steps': method['gradient_accumulation_steps'],
        'generation_batch_size': method['generation_batch_size'],
        'num_generations': method['num_generations'], 'num_iterations': 1,
        'max_steps': steps, 'learning_rate': method['learning_rate'],
        'lr_scheduler_type': 'constant', 'warmup_ratio': 0, 'beta': method['beta'],
        'loss_type': method['loss_type'], 'scale_rewards': method['scale_rewards'],
        'dynamic_sample': method['dynamic_sample'], 'use_vllm': method['use_vllm'],
        'max_completion_length': method['max_completion_length'],
        'temperature': method['temperature'], 'top_p': method['top_p'],
        'top_k': method['top_k'], 'split_dataset_ratio': 0,
        'dataset_num_proc': 1, 'dataloader_num_workers': 0,
        'dataloader_persistent_workers': False,
        'dataset_shuffle': False, 'train_dataloader_shuffle': False,
        'logging_steps': 1 if steps < method['steps'] else 10,
        'log_completions': True, 'report_to': ['none'],
        'save_strategy': 'steps',
        'save_steps': 250 if steps == 1000 else steps,
        'save_total_limit': 4 if steps == 1000 else 1,
        'seed': seed, 'data_seed': method['data_seed'],
        'remove_unused_columns': False, 'weight_decay': 0.0,
        'output_dir': str(output),
    }
